#!/usr/bin/env bash
# Verify certificate role separation, BYO import semantics, key/cert matching,
# validity, strength, and persistence using real OpenSSL material. No test key
# leaves the local fixture directory and the container has no network.
set -euo pipefail

image=${1:-postfix-m365-relay:test}
container=postfix-m365-relay-certificate-test
fixture=$PWD/tests/.tmp-certificates
volumes=(
  postfix-m365-relay-certificate-state
  postfix-m365-relay-certificate-spool
  postfix-m365-relay-certificate-mismatch-state
  postfix-m365-relay-certificate-inbound-mismatch-state
  postfix-m365-relay-certificate-weak-state
)

cleanup() {
  docker rm -f "$container" >/dev/null 2>&1 || true
  docker volume rm "${volumes[@]}" >/dev/null 2>&1 || true
  rm -rf "$fixture"
}
trap cleanup EXIT
cleanup
install -d -m 0700 "$fixture"

make_pair() {
  local stem=$1 bits=$2 subject=$3
  openssl req -x509 -newkey "rsa:$bits" -nodes -days 30 -subj "/CN=$subject" \
    -keyout "$fixture/$stem.key" -out "$fixture/$stem.crt" >/dev/null 2>&1
  chmod 0600 "$fixture/$stem.key"
  chmod 0644 "$fixture/$stem.crt"
}
# oauth pairs stay RSA-4096 on purpose: the boot guard now requires >= 2048, so
# these legacy-strength keys must still import cleanly (the upgrade path). The
# weak pair is below 2048 and must be refused.
make_pair oauth-one 4096 'OAuth Import One'
make_pair oauth-two 4096 'OAuth Import Two'
make_pair inbound-one 2048 'Inbound TLS One'
make_pair inbound-two 2048 'Inbound TLS Two'
make_pair weak 1024 'Weak OAuth'

common=(--network none
  -e MAIL_RELAY_TENANT=00000000-0000-0000-0000-000000000000
  -e MAIL_RELAY_CLIENT_ID=11111111-1111-1111-1111-111111111111
  -e MAIL_SEND_MAILBOX=relay-test@example.invalid
  -e MAIL_SENDER_APP=app@relay.example.local
  -e MAIL_INBOUND_AUTH=ip -e MAIL_INBOUND_TLS=may
  -e MAIL_RELAY_CLIENT_KEY_FILE=/run/secrets/oauth.key
  -e MAIL_RELAY_CLIENT_CERT_FILE=/run/secrets/oauth.crt
  -e MAIL_INBOUND_TLS_KEY=/run/secrets/inbound.key
  -e MAIL_INBOUND_TLS_CERT=/run/secrets/inbound.crt
  -e MAIL_VERIFY_SEND=no -e MAIL_TOKEN_ALERT_AFTER=99
  -e MAIL_TOKEN_LOOP_SECONDS=300 -e MAIL_ROTATION_LOOP_SECONDS=300 -e MAIL_VERIFY_LOOP_SECONDS=300
  --tmpfs /run/mail-relay:rw,nosuid,noexec,mode=0750)

start_import() {
  local oauth_stem=$1 inbound_stem=$2
  docker rm -f "$container" >/dev/null 2>&1 || true
  docker run -d --name "$container" "${common[@]}" \
    -v postfix-m365-relay-certificate-state:/var/lib/mail-relay \
    -v postfix-m365-relay-certificate-spool:/var/spool/postfix \
    -v "$fixture/$oauth_stem.key":/run/secrets/oauth.key:ro \
    -v "$fixture/$oauth_stem.crt":/run/secrets/oauth.crt:ro \
    -v "$fixture/$inbound_stem.key":/run/secrets/inbound.key:ro \
    -v "$fixture/$inbound_stem.crt":/run/secrets/inbound.crt:ro \
    "$image" >/dev/null
  for _attempt in {1..40}; do
    [[ $(docker inspect -f '{{.State.Running}}' "$container") == true ]] || {
      docker logs "$container"; return 1;
    }
    docker exec "$container" grep -q '^# <<< postfix-m365-relay (managed) <<<$' \
      /etc/postfix/main.cf >/dev/null 2>&1 && return 0
    sleep 1
  done
  docker logs "$container"
  return 1
}

start_import oauth-one inbound-one
source_thumbprint=$(openssl x509 -in "$fixture/oauth-one.crt" -noout -fingerprint -sha256)
state_thumbprint=$(docker exec "$container" openssl x509 \
  -in /var/lib/mail-relay/secrets/mail_relay_client_cert.pem -noout -fingerprint -sha256)
[[ $state_thumbprint == "$source_thumbprint" ]]
[[ $(docker exec "$container" postconf -h smtpd_tls_cert_file) == /run/secrets/inbound.crt ]]
[[ $(docker exec "$container" postconf -h smtpd_tls_key_file) == /run/secrets/inbound.key ]]
[[ $(docker exec "$container" stat -c '%a %U:%G' /var/lib/mail-relay/secrets/mail_relay_client_key.pem) == '600 postfix:postfix' ]]
echo 'ok separate BYO OAuth and inbound TLS pairs are selected and protected'

# Restart with a different import source. State must retain the first pair;
# otherwise every recreation would undo a certificate generated by self-rotation.
docker stop --timeout 10 "$container" >/dev/null
start_import oauth-two inbound-one
state_after_restart=$(docker exec "$container" openssl x509 \
  -in /var/lib/mail-relay/secrets/mail_relay_client_cert.pem -noout -fingerprint -sha256)
[[ $state_after_restart == "$source_thumbprint" ]]
echo 'ok OAuth import is first-boot-only and cannot overwrite rotated state'

expect_pair_failure() {
  local state=$1 needle=$2 oauth_key=$3 oauth_cert=$4 inbound_key=$5 inbound_cert=$6
  docker rm -f "$container" >/dev/null 2>&1 || true
  if docker run --rm --name "$container" "${common[@]}" \
    -v "$state":/var/lib/mail-relay \
    -v "$fixture/$oauth_key":/run/secrets/oauth.key:ro \
    -v "$fixture/$oauth_cert":/run/secrets/oauth.crt:ro \
    -v "$fixture/$inbound_key":/run/secrets/inbound.key:ro \
    -v "$fixture/$inbound_cert":/run/secrets/inbound.crt:ro \
    "$image" > "$fixture/failure.log" 2>&1; then
    echo "expected certificate failure: $needle" >&2
    return 1
  fi
  grep -Fq "$needle" "$fixture/failure.log" || { cat "$fixture/failure.log"; return 1; }
  echo "ok refused: $needle"
}

expect_pair_failure postfix-m365-relay-certificate-mismatch-state \
  'OAuth private key and certificate do not match' \
  oauth-one.key oauth-two.crt inbound-one.key inbound-one.crt
expect_pair_failure postfix-m365-relay-certificate-inbound-mismatch-state \
  'inbound TLS private key and certificate do not match' \
  oauth-one.key oauth-one.crt inbound-one.key inbound-two.crt
expect_pair_failure postfix-m365-relay-certificate-weak-state \
  'OAuth private key must be RSA-2048 or stronger' \
  weak.key weak.crt inbound-one.key inbound-one.crt

docker rm -f "$container" >/dev/null 2>&1 || true
echo 'ok certificate validation and persistence matrix'

# Now use image-owned inbound TLS state and force it into an artificial renewal
# window. The current certificate is valid for 30 days; asking for a 31-day
# threshold with a 40-day replacement validity makes the test deterministic
# without changing the system clock or waiting. Manual docker exec does not
# inherit variables exported by PID 1 after boot, so effective paths and the
# ownership marker are passed exactly as the supervisor passes them in reality.
docker run -d --name "$container" --network none \
  -e MAIL_RELAY_TENANT=00000000-0000-0000-0000-000000000000 \
  -e MAIL_RELAY_CLIENT_ID=11111111-1111-1111-1111-111111111111 \
  -e MAIL_SEND_MAILBOX=relay-test@example.invalid \
  -e MAIL_SENDER_APP=app@relay.example.local \
  -e MAIL_INBOUND_AUTH=ip -e MAIL_INBOUND_TLS=may \
  -e MAIL_INBOUND_TLS_VALIDITY_DAYS=30 -e MAIL_INBOUND_TLS_RENEW_AT_DAYS=10 \
  -e MAIL_VERIFY_SEND=no -e MAIL_TOKEN_ALERT_AFTER=99 \
  -e MAIL_TOKEN_LOOP_SECONDS=300 -e MAIL_ROTATION_LOOP_SECONDS=300 -e MAIL_VERIFY_LOOP_SECONDS=300 \
  -v postfix-m365-relay-certificate-state:/var/lib/mail-relay \
  -v postfix-m365-relay-certificate-spool:/var/spool/postfix \
  --tmpfs /run/mail-relay:rw,nosuid,noexec,mode=0750 "$image" >/dev/null
for _attempt in {1..40}; do
  docker exec "$container" postfix status >/dev/null 2>&1 && break
  sleep 1
done
managed_key=/var/lib/mail-relay/inbound-tls/key.pem
managed_cert=/var/lib/mail-relay/inbound-tls/cert.pem
key_before=$(docker exec "$container" sh -c \
  'openssl pkey -in /var/lib/mail-relay/inbound-tls/key.pem -pubout -outform DER | openssl dgst -sha256')
cert_before=$(docker exec "$container" openssl x509 -in "$managed_cert" -noout -fingerprint -sha256)
docker exec \
  -e MAIL_INBOUND_TLS=may -e MAIL_INBOUND_TLS_MANAGED=yes \
  -e MAIL_INBOUND_TLS_KEY_EFFECTIVE="$managed_key" \
  -e MAIL_INBOUND_TLS_CERT_EFFECTIVE="$managed_cert" \
  -e MAIL_INBOUND_TLS_VALIDITY_DAYS=40 -e MAIL_INBOUND_TLS_RENEW_AT_DAYS=31 \
  "$container" /usr/local/libexec/mail-relay/rotate-inbound-tls.sh
key_after=$(docker exec "$container" sh -c \
  'openssl pkey -in /var/lib/mail-relay/inbound-tls/key.pem -pubout -outform DER | openssl dgst -sha256')
cert_after=$(docker exec "$container" openssl x509 -in "$managed_cert" -noout -fingerprint -sha256)
[[ $key_after == "$key_before" && $cert_after != "$cert_before" ]]
docker exec "$container" test -s "$managed_cert.previous"
docker exec "$container" openssl x509 -checkend $((31 * 86400)) -noout -in "$managed_cert"
docker exec "$container" postfix status
echo 'ok generated inbound TLS renews atomically with a stable key and reloads Postfix'

# The export-cert helper and its relay-admin alias must hand an operator the
# PUBLIC OAuth certificate for Entra upload — byte-identical to the on-disk copy,
# a parseable certificate, and never leaking the private key — so bootstrap works
# without reading logs or knowing the state path.
oauth_cert=/var/lib/mail-relay/secrets/mail_relay_client_cert.pem
canonical_export=$(docker exec "$container" cat "$oauth_cert")
bare_export=$(docker exec "$container" export-cert)
admin_export=$(docker exec "$container" relay-admin export-cert)
[[ $bare_export == "$canonical_export" && $admin_export == "$canonical_export" ]]
[[ $bare_export == *'-----BEGIN CERTIFICATE-----'* ]]
! grep -qiE 'PRIVATE KEY' <<<"$bare_export"
docker exec "$container" sh -c "openssl x509 -in '$oauth_cert' -noout -fingerprint -sha256" >/dev/null
echo 'ok export-cert and relay-admin export-cert emit only the public OAuth certificate'

# relay-admin remove-key is a thin wrapper whose whole purpose is to reject any
# argument that is not a Graph key UUID before it reaches the rotation tool, so a
# typo or an option-looking value can never be reinterpreted as a Python flag.
# Malformed input must exit with the usage code (64) and never invoke rotation.
expect_remove_key_rejected() {
  local rc=0
  docker exec "$container" relay-admin remove-key "$@" >/dev/null 2>&1 || rc=$?
  [[ $rc -eq 64 ]] || { echo "relay-admin remove-key accepted invalid input: [$*] rc=$rc" >&2; exit 1; }
}
expect_remove_key_rejected                                            # missing argument
expect_remove_key_rejected not-a-uuid                                 # not a UUID at all
expect_remove_key_rejected --list-keys                                # option smuggling
expect_remove_key_rejected '11111111-1111-1111-1111-11111111111'      # one hex digit short
expect_remove_key_rejected 'zzzzzzzz-1111-1111-1111-111111111111'     # non-hex characters
expect_remove_key_rejected 11111111-1111-1111-1111-111111111111 extra # too many arguments
# A well-formed UUID clears the validation gate. With no test network the
# rotation tool then fails (or is timed out), but never with the usage exit code
# 64 — proving the wrapper handed the id through instead of rejecting it.
gate_rc=0
docker exec "$container" sh -c \
  'timeout 20 relay-admin remove-key 22222222-2222-2222-2222-222222222222' >/dev/null 2>&1 || gate_rc=$?
[[ $gate_rc -ne 64 ]] || { echo 'relay-admin remove-key rejected a valid UUID' >&2; exit 1; }
echo 'ok relay-admin remove-key validates the key id before invoking rotation'

# relay-admin rotate exposes only lifecycle-tuning flags and must refuse the
# rotation tool's credential-overwriting options (--generate-only, --key-path,
# --cert-path, ...), so a remote admin can never repoint or regenerate the live
# key material through the wrapper. Forbidden or malformed arguments exit 64.
expect_rotate_rejected() {
  local rc=0
  docker exec "$container" relay-admin rotate "$@" >/dev/null 2>&1 || rc=$?
  [[ $rc -eq 64 ]] || { echo "relay-admin rotate accepted forbidden args: [$*] rc=$rc" >&2; exit 1; }
}
expect_rotate_rejected --generate-only                   # offline key generation
expect_rotate_rejected --key-path /tmp/x                  # repoint the private key
expect_rotate_rejected --cert-path /tmp/x                 # repoint the certificate
expect_rotate_rejected --reuse-key                        # generation modifier
expect_rotate_rejected --key-bits 2048                    # unlisted option
expect_rotate_rejected --env-file /tmp/x                  # unlisted option
expect_rotate_rejected --subject smuggled                 # unlisted option
expect_rotate_rejected --validity abc                     # non-numeric value
expect_rotate_rejected --validity                         # missing value
expect_rotate_rejected --renew-at -5                      # non-numeric (leading dash)
expect_rotate_rejected --to                               # missing recipient
expect_rotate_rejected --to --force                       # option smuggled as the value
expect_rotate_rejected --definitely-not-a-flag            # unknown flag

# Allowlisted flags must clear the wrapper and reach the rotation tool. --dry-run
# changes nothing; the tool then exits for its own reasons (or is timed out on the
# absent test network) but never with the usage code, proving the args passed
# through instead of being rejected.
expect_rotate_gate_open() {
  local rc=0
  docker exec "$container" sh -c "timeout 15 relay-admin rotate $*" >/dev/null 2>&1 || rc=$?
  [[ $rc -ne 64 ]] || { echo "relay-admin rotate wrongly rejected allowlisted args: [$*]" >&2; exit 1; }
}
expect_rotate_gate_open --dry-run                         # bare flag branch
expect_rotate_gate_open --dry-run --validity 40           # numeric-value branch
expect_rotate_gate_open --force --dry-run                 # multiple flags
echo 'ok relay-admin rotate allowlists lifecycle flags and blocks credential-overwriting options'
